CREATE DATABASE BBDD_Equipo13
GO
USE BBDD_Equipo13
GO
--TABLA PARA TIPOS DE VEHICULOS
CREATE TABLE TIPOS_VEHICULOS(
    IDTIPO INT PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(20) NOT NULL,
    CANT_ASIENTOS INT NULL
)
GO
--RESTRICCIONES TIPOS DE VEHICULOS
ALTER TABLE TIPOS_VEHICULOS
ADD CHECK(CANT_ASIENTOS >= 4)
GO

--TABLA PARA VEHICULOS
CREATE TABLE VEHICULOS(
    IDVEHICULO INT PRIMARY KEY IDENTITY(1,1),
    IDTIPO INT NOT NULL,
    MODELO INT NOT NULL DEFAULT(2022),
    PATENTE VARCHAR(7) NOT NULL,
    ESTADO BIT NULL DEFAULT (1)
)
GO
--RESTRICCIONES VEHICULOS
ALTER TABLE VEHICULOS
ADD CONSTRAINT FK_VEHICULO_TIPO FOREIGN KEY (IDTIPO) REFERENCES TIPOS_VEHICULOS (IDTIPO)
GO
ALTER TABLE VEHICULOS
ADD CHECK(MODELO <= YEAR(GETDATE()))
GO

--TABLA PARA DOMICILIO
CREATE TABLE DOMICILIO (
    IDDOMICILIO BIGINT PRIMARY KEY IDENTITY(1,1),
    DIRECCION VARCHAR(100) NOT NULL,
    LOCALIDAD VARCHAR(80) NOT NULL,
    PROVINCIA VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,
)
GO  

-- TABLA PARA PERSONAS
CREATE TABLE PERSONA (
    IDPERSONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DNI VARCHAR(10) NULL,
    FECHANACIMIENTO DATE NULL,
    DOMICILIO BIGINT FOREIGN KEY REFERENCES DOMICILIO(IDDOMICILIO) NULL,
    NACIONALIDAD VARCHAR(40) NULL
)
GO

--TABLA PARA ZONAS
CREATE TABLE ZONAS(
    IDZONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBREZONA VARCHAR(15) NOT NULL
)
GO

-- TABLA PARA CHOFERES
CREATE TABLE CHOFER (
    IDCHOFER INT PRIMARY KEY IDENTITY (1,1),
    IDPERSONA INT FOREIGN KEY REFERENCES PERSONA (IDPERSONA) NOT NULL,
    IDZONA INT FOREIGN KEY REFERENCES ZONAS (IDZONA) NOT NULL,
    IDVEHICULO INT FOREIGN KEY REFERENCES VEHICULOS (IDVEHICULO) NULL
)
GO

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY IDENTITY (1, 1),
	IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONA (IDPERSONA),
    IDZONA INT NOT NULL FOREIGN KEY REFERENCES ZONAS (IDZONA) DEFAULT 2
)
GO

