CREATE DATABASE BBDD_Equipo13
GO
USE BBDD_Equipo13
GO
--TABLA PARA TIPOS DE VEHICULOS
CREATE TABLE TIPOS_VEHICULOS(
    IDTIPO INT PRIMARY KEY IDENTITY(1,1),
    TIPO VARCHAR(20) NOT NULL,
    CANT_ASIENTOS INT NULL
)
GO
--RESTRICCIONES TIPOS DE VEHICULOS
ALTER TABLE TIPOS_VEHICULOS
ADD CHECK(CANT_ASIENTOS >= 4)
GO

--TABLA PARA VEHICULOS
CREATE TABLE VEHICULOS(
    IDVEHICULO INT PRIMARY KEY IDENTITY(1,1),
    IDTIPO INT NOT NULL,
    MODELO INT NOT NULL DEFAULT(2022),
    PATENTE VARCHAR(7) NOT NULL,
    ESTADO BIT NULL DEFAULT (1)
)
GO
--RESTRICCIONES VEHICULOS
ALTER TABLE VEHICULOS
ADD CONSTRAINT FK_VEHICULO_TIPO FOREIGN KEY (IDTIPO) REFERENCES TIPOS_VEHICULOS (IDTIPO)
GO
ALTER TABLE VEHICULOS
ADD CHECK(MODELO <= YEAR(GETDATE()))
GO

--TABLA PARA DOMICILIO
CREATE TABLE DOMICILIO (
    IDDOMICILIO BIGINT PRIMARY KEY IDENTITY(1,1),
    DIRECCION VARCHAR(100) NOT NULL,
    LOCALIDAD VARCHAR(80) NOT NULL,
    PROVINCIA VARCHAR(25) NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,
)
GO  

-- TABLA PARA PERSONAS
CREATE TABLE PERSONA (
    IDPERSONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRES VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    DNI VARCHAR(10) NULL,
    FECHANACIMIENTO DATE NULL,
    DOMICILIO BIGINT FOREIGN KEY REFERENCES DOMICILIO(IDDOMICILIO) NULL,
    TELEFONO VARCHAR(15) NOT NULL DEFAULT 1588888,
    EMAIL VARCHAR(30) NULL DEFAULT 'ejemplo@ej.com',
    NACIONALIDAD VARCHAR(40) NULL
)
GO
-- MODIFICACIONES PERSONA
ALTER TABLE PERSONA
ADD TELEFONO VARCHAR(15) NOT NULL DEFAULT 1588888
GO
ALTER TABLE PERSONA
ADD EMAIL VARCHAR(30) NULL DEFAULT 'ejemplo@ej.com'

--TABLA PARA ZONAS
CREATE TABLE ZONAS(
    IDZONA INT PRIMARY KEY IDENTITY(1,1),
    NOMBREZONA VARCHAR(15) NOT NULL
)
GO

-- TABLA PARA CHOFERES
CREATE TABLE CHOFER (
    IDCHOFER INT PRIMARY KEY IDENTITY (1,1),
    IDPERSONA INT FOREIGN KEY REFERENCES PERSONA (IDPERSONA) NOT NULL,
    IDZONA INT FOREIGN KEY REFERENCES ZONAS (IDZONA) NOT NULL,
    IDVEHICULO INT FOREIGN KEY REFERENCES VEHICULOS (IDVEHICULO) NULL
)
GO

-- TABLA PARA CLIENTES
CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY IDENTITY (1, 1),
	IDPERSONA INT NOT NULL FOREIGN KEY REFERENCES PERSONA (IDPERSONA),
    IDZONA INT NOT NULL FOREIGN KEY REFERENCES ZONAS (IDZONA) DEFAULT 2
)
GO

-- TABLA PARA VIAJES
CREATE TABLE VIAJES (
    IDVIAJE BIGINT PRIMARY KEY IDENTITY(1,1),
    IDCHOFER INT NOT NULL FOREIGN KEY REFERENCES CHOFER (IDCHOFER),
    IDCLIENTE INT NULL FOREIGN KEY REFERENCES CLIENTE (IDCLIENTE),
    TIPOVIAJE VARCHAR(15) NULL,
    IMPORTE MONEY NOT NULL,
    IDDOMORIGEN BIGINT NOT NULL FOREIGN KEY REFERENCES DOMICILIO (IDDOMICILIO),
    IDDOMDESTINO1 BIGINT NOT NULL FOREIGN KEY REFERENCES DOMICILIO (IDDOMICILIO),
    IDDOMDESTINO2 BIGINT NULL FOREIGN KEY REFERENCES DOMICILIO (IDDOMICILIO),    
    IDDOMDESTINO3 BIGINT NULL FOREIGN KEY REFERENCES DOMICILIO (IDDOMICILIO),    
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ASIGNADO',
    FECHAHORAVIAJE DATE NOT NULL DEFAULT GETDATE(),
    PAGADO BIT NOT NULL DEFAULT 0,
    MEDIODEPAGO VARCHAR(25) NOT NULL
)
GO
-- RESTRICCIONES VIAJES
ALTER TABLE VIAJES
ADD CHECK (IMPORTE > 0)
GO
ALTER TABLE VIAJES
ADD CHECK (FECHAHORAVIAJE <= GETDATE())
GO

-- STORED PROCEDURE
GO
CREATE PROCEDURE SP_BAJAFISICACLIENTE (@IDCLIENTE INT)
AS BEGIN
DECLARE @IDPERSONA INT
SET @IDPERSONA = (SELECT IDPERSONA FROM CLIENTE WHERE @IDCLIENTE = IDCLIENTE)
DELETE FROM CLIENTE WHERE @IDCLIENTE = IDCLIENTE
DELETE FROM PERSONA WHERE @IDPERSONA = IDPERSONA
END

-- CAMPO ESTADO EN TABLA CHOFER
GO
ALTER TABLE CHOFER
ADD ESTADO BIT NOT NULL DEFAULT 1

    --AGREGAR HORA A FECHAHORAVIAJE
--ELIMINA LAS CONSTRAINT PARA PODER ALTERAR LA COLUMNA
ALTER TABLE VIAJES DROP CONSTRAINT DF__VIAJES__FECHAHOR__1CBC4616
ALTER TABLE VIAJES DROP CONSTRAINT CK__VIAJES__FECHAHOR__1F98B2C1
--ALTERA LA COLUMNA
ALTER TABLE VIAJES
ALTER COLUMN FECHAHORAVIAJE DATETIME;
--AGREGA QUE NO PUEDA SER NULL
ALTER TABLE VIAJES ALTER COLUMN FECHAHORAVIAJE DATETIME NOT NULL